
const bankMappings = {
  ybl:"YES BANK",
  rbl:"RBL BANK",
  ibl:"ICICI BANK",
  idfc:"IDFC BANK",
  axl:"AXIS BANK",
  sbi:"SBI BANK",
  uco:"UNITED COMMERCIAL BANK",
  cub:"CITY UNION BANK",
  federal:"FEDERAL BANK",
  aubank:"AU BANK",
  sib:"SOUTH INDIAN BANK",
  scb:"STANDARD CHARTERED BANK",
  iob:"INDIAN OVERSEAS BANK",
  indus:"INDUSIND BANK",
  csbpay:"CATHOLIC SYRIAN BANK",
  cnrb:"CANARA BANK",
  fbl:"FEDERAL BANK",
  wasbi:"SBI BANK",
  okhdfcbank:"HDFC BANK",
  axisbank:"AXIS BANK",
  okaxis:"AXIS BANK",
  kotak:"KOTAK BANK",
  yesbank:"YES BANK",
  boi:"BOI BANK",
  postbank:"INDIA POST PAYMENTS BANK",
  centralbank:"CBI BANK",
  yesbankltd:"YES BANK",
  kvb:"KARUR VYSYA BANK",
  cmsidfc:"IDFC BANK",
  hdfcbank:"HDFC BANK",
  oksbi:"SBI BANK",
  icici:"ICICI BANK",
  okaxis     :"AXIS BANK",
  okbizaxis:"AXIS BANK",
  okaxis  :"AXIS BANK",
  barodampay:"BARODA BANK",
  OKICICI:"ICICI BANK",
  waicici:"ICICI BANK",
  waaxis:"AXIS BANK",
  ibl :"ICICI BANK",
  idbi:"IDBI BANK",
  idfcfirst:"IDFC BANK",
  okbizicici:"ICICI BANK",
  idfcbank:"IDFC BANK",
  SIBL:"SOUTH INDIAN BANK",
  utkarshbank:"UTKARSH SMALL FINANCE BANK",
  DBS:"DBS BANK",
  idfcbank        :"IDFC BANK",
  indianbank:"INDIAN BANK",
  axisbank  :"AXIS BANK",
  wahdfcbank:"HDFC BANK",
  ratn:"RBL BANK",
  pnb:"PNB BANK",
  kotak :"KOTAK BANK",
  idfcbank :"IDFC BANK",
  aubank :"AU BANK",
  idfcfisrt:"IDFC BANK",
  yesbankltd:"YES BANK",
  jupiteraxis:"AXIS BANK",
  dbs  :"DBS BANK",
  idbi :"IDBI BANK",
  airtel:"AIRTEL PAYMENTS BANK",
  andb:"ANDHRA BANK",
  bandhan:"BANDHAN BANK",
  abfspay:"AXIS BANK",
  barodamp:"BARODA BANK",
  bob:"BARODA BANK",
  kmbl:"KOTAK BANK",
  axisb:"AXIS BANK",
  denabank:"DENA BANK",
  dcb:"DCB BANK",
  dlb:"DHANLAXMI BANK",
  equitas:"EQUITAS BANK",
  finobank:"FINO PAYMENTS BANK",
  rmhdfcbank:"HDFC BANK",
  freecharge:"AXIS BANK",
  hsbc:"HSBC BANK",
  idfcbabk:"IDFC BANK",
  jsb:"JANATA SAHAKARI BANK",
  jkb:"JAMMU & KASHMIR BANK",
  hdfcbankjd:"HDFC BANK",
  kaypay:"KOTAK BANK",
  kbl:"KARNATAKA BANK",
  lvb:"LAXMI VILAS BANK",
  mahb:"MAHARASHTRA BANK",
  myicici:"ICICI BANK",
  ikwik:"HDFC BANK",
  axisgo:"AXIS BANK",
  obc:"ORIENTAL BANK",
  paytm:"PAYTM PAYMENTS BANK",
  psb:"PUNJAB & SIND BANK",
  pockets:"ICICI BANK",
  pingpay:"AXIS BANK",
  s2b:"STANDARD CHARTERED BANK",
  tapicici:"ICICI BANK",
  sliceaxis:"AXIS BANK",
  syndicate:"SYNDICATE BANK",
  tjsb:"TJSB BANK",
  timecosmos:"COSMOS BANK",
  unionbank:"UNION BANK",
  uboi:"UNION BANK",
  united:"UNITED BANK",
  ubi:"UNITED BANK",
  utbi:"UNITED BANK",
  vijb:"VIJAYA BANK",
  SMCB:"SHIVALIK BANK",
  esaf:"ESAF SMALL FINANCE BANK",
  hdfc:"HDFC BANK",
  yesbank :"YES BANK",
  equitasbank:"EQUITAS BANK",
  okhdfc:"HDFC BANK",
  upi:"NA",
  pz:"HDFC BANK",
  jio:"JIO PAYMENTS BANK",
  fbpe:"NA",
  idfcfrist:"IDFC BANK",
  fedral:"FEDERAL BANK",
  fedeal:"NA",
  okhdfcban:"HDFC BANK",
  tmb:"TAMILNAD MERCANTILE BANK",
  indianbk:"INDIAN BANK",
  okisbi:"SBI BANK",
  bhim:"NA",
  indb:"INDUSIND BANK",
  FDRL:"FEDERAL BANK",
  cbin:"CBI BANK",
  axsibank:"AXIS BANK",
  apl:"AXIS BANK",
  yapl:"YES BANK",
  rapl:"RBL BANK",
  goaxb:"AXIS BANK LIMITED",
  yesg:"YES BANK",
  zoicici:"ICICI BANK",
  payzapp:"HDFC BANK",
  upo:"NA",
  mbk:"MOBIKWIK",
  fincarem:"FINCARE BANK",
  Ujjivan:"UJJIVAN BANK",
  // gmail.com:"NA",
  SRCB:"SARASWAT CO-OPERATIVE BANK",
  
    // Add more mappings as needed
  };
  
  module.exports = bankMappings;
  