const ifsc ={
    INDB:"INDUSIND BANK",
    HDFC:"HDFC BANK",
    FDRL:"FEDERAL BANK",
    SIBL:"SOUTH INDIAN BANK",
    IBKL:"IDBI BANK",
    CBIN:"CBI BANK",
    AIRP:"AIRTEL PAYMENTS BANK",
    YESB:"YES BANK",
    RATN:"RBL BANK",
    CNRB:"CANARA BANK",
    CSBK:"CATHOLIC SYRIAN BANK",
    AUBL:"AU BANK",
    KKBK:"KOTAK BANK",
    SBIN:"SBI BANK",
    PUNB:"PNB BANK",
    UTIB:"AXIS BANK",
    ICIC:"ICICI BANK",
    HDFC:"HDFC BANK",
    IDFB:"IDFC BANK",
    barb:"BARODA BANK",
    UTKS:"UTKARSH SMALL FINANCE BANK",
    ESFB:"EQUITAS BANK",
    SMCB:"SHIVALIK BANK",
    CIUB:"CITY UNION BANK",
    UBIN:"UNION BANK"
    
}

export default ifsc;